### ISSUE TITLE
Is there a way to select the location manually?

### ISSUE THREAD

**Issue by hrqmonteiro** [vascomfnunes/tmux-clima#8]
It just doesn't work with my IP automatically:

![image](https://github.com/vascomfnunes/tmux-clima/assets/17055027/6b102917-903d-4c02-8fb9-00677b5b2cc8)
![image](https://github.com/vascomfnunes/tmux-clima/assets/17055027/1ea1d03a-716d-44bb-a356-8ab4dcab1023)

**Comment by vascomfnunes** [comment]
Not at the moment, I'm afraid.

Double check if your location's data is correctly retrieved from here: https://ifconfig.co/json

Also, make sure to have `jq` installed.

**Comment by xafarr** [comment]
That'd be a nice feature to have. I'll have a look when I have some time.

**Comment by xafarr** [comment]
I briefly looked into OpenWeather Geocoding API and it seems easy to implement.

**Comment by xafarr** [comment]
#9

**Comment by xafarr** [comment]
I have raised a draft PR that implements this feature #9

**Comment by vascomfnunes** [comment]
Nice one! Thanks, it's now merged.
